### PR TITLE
portable-ruby: enable coverage.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Do this for e.g. `simplecov`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@Homebrew/linux @sjackman Without this you cannot `brew tests --coverage`. You can feel free to make a new build or not depending on your requirements but I'd advise decide either way before merging the next tag to Linuxbrew.

**Comment by sjackman** [comment]
I'll build a new bottle. Thanks for the heads up.

**Comment by sjackman** [comment]
Should this be a `revision 1` rather than a `rebuild 1`?

**Comment by MikeMcQuaid** [comment]
@sjackman I think a `rebuild 1` is fine in this relatively rare case because we're not wanting to force upgrades.

**Comment by sjackman** [comment]
I've built the `portable-ruby` 2.3.3 rebuild 1 bottle for Linux.
https://github.com/Homebrew/brew/pull/3326

**Pull request merged**
